[package]
name = "cyberpunk_display"
version = "0.1.0"
authors = ["WestXu <xu-lai-xi@qq.com>"]
edition = "2018"

[dependencies]
ordered-float = "*"
ansi_term = "*"
tungstenite = '*'
url = '*'
flate2 = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
native-tls = "*"

[dev-dependencies]
rand = "*"
