[package]
name = "cyberpunk_display_rust"
version = "0.1.0"
authors = ["WestXu <xu-lai-xi@qq.com>"]
edition = "2018"

[lib]
name = "cyberpunk_display_rust"
crate-type = ["lib", "cdylib"]

[dependencies]
rand = "0.8.3"
ordered-float = "2.0"
ansi_term = "0.12.1"

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]
