[package]
name = "cyberpunk_display"
version = "0.1.0"
authors = ["WestXu <xu-lai-xi@qq.com>"]
edition = "2021"

[dependencies]
ordered-float = "*"
ansi_term = "*"
tungstenite = '*'
url = '*'
serde = { version = "*", features = ["derive"] }
serde_json = "*"
native-tls = "*"
reqwest = { version = "*", features = ["blocking"] }
clap = { version = "3.0.14", features = ["derive"] }
serialport = { version = "4.2", optional = true }

[dev-dependencies]
rand = "*"

[features]
nixie = ["dep:serialport"]
